language: node_js
dist: trusty
services:
- mongodb
- postgresql
- redis-server
- docker
addons:
  postgresql: '9.5'
  apt:
    packages:
    - postgresql-9.5-postgis-2.3
branches:
  only:
  - master
  - "/^[0-9]+.[0-9]+.[0-9]+(-.*)?$/"
  - 3.x
  - "/^greenkeeper/.*$/"
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.mongodb/versions"
stage: test
env:
  global:
  - COVERAGE_OPTION='./node_modules/.bin/nyc'
  matrix:
  - MONGODB_VERSION=4.0.4
  - MONGODB_VERSION=3.6.9
  - PARSE_SERVER_TEST_DB=postgres
  - PARSE_SERVER_TEST_CACHE=redis
  - NODE_VERSION=11.4.0
matrix:
  allow_failures:
  - env: NODE_VERSION=11.4.0
before_install:
- nvm install $NODE_VERSION
- nvm use $NODE_VERSION
- npm install -g greenkeeper-lockfile@1
before_script:
- node -e 'require("./lib/index.js")'
- psql -c 'create database parse_server_postgres_adapter_test_database;' -U postgres
- psql -c 'CREATE EXTENSION postgis;' -U postgres -d parse_server_postgres_adapter_test_database
- psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d parse_server_postgres_adapter_test_database
- silent=1 mongodb-runner --start
- greenkeeper-lockfile-update
script:
- npm run lint
- npm run coverage
after_script:
- greenkeeper-lockfile-upload
- bash <(curl -s https://codecov.io/bash)
jobs:
  include:
  - stage: release
    node_js: '10'
    env:
    before_script: skip
    after_script: skip
    script:
    - "./release_docs.sh"
    deploy:
    - provider: pages
      skip_cleanup: true
      github_token:
        secure: VHNpkz4+Q0ZxoO7RPP8RlZWuH/jEpLO1A0a1wRpVvP05iMUimqlHRDg3SS491CBTa6VupDlg2kbgcwX8AtZENf9GZWHr4RpOdk8Q9FIcR//9peyXpFbqkMBybJyvxABaNuLDMpGkAkKofmxTwMoMoQ/bdyhVrnEklXlyiRuwnDSjcR70Ti9OFOkYValvgb6Qa4HEX0qs4rRGak+FgNrZzX1cZc7LTOYyiuXwdTvt/UqH5mDW+mXFNScwUZnWTyS+kB+tDJYe/wtKeuFv6J+wHI9TkVHmDsZK6TwnnEEmh+D38cBqlU90ZUKXZYOd4v9E0TFlM4kNxBNmp5N/jYUPThJ+Gc56HULMwqQmdwb+HFa/ZdQImM0Q/ibGgYZtxHxXH9j4K3mOLTpcOOqYGQcw3DBkQGMQM2/rY1b4LUlCqhngs6stEGFkkGCORAV5NE4EMIv0B9/BhfBN4v8nZPm9xin/mqyecaxUxwOGOvJZs1hRO20OEJE30Tk6H6dmkRen8Q2u5Uy6gYH2RU/6lumNTlY223nQ1JvtexKDa6fVWzRKYZ3KfbJ5umoA48i6p1ll9xvAoACy9CUnIdz3WWro86NBA/AK3efRKi0hjA+InjQZ1T8IkqlWN4Habr54E5Vzyz7VQ7/541JN1HvVsTctsnMOErXCBv54wU4Anw2r8lU=
      local_dir: docs/
      on:
        all_branches: true
    - provider: npm
      api_key:
        secure: Yrng6jsnMAtzrrln9DwRuY4xpcxl/WYS/1A5fckyQF6DsLmNlvqVtu3MWF+zdJgANF63G3jIee11tNBpYRecHl8FjPGwO0kc1vEgvIRVnveyR0bwIIDH6s/mR9dg4rZikflwG4XExsLyaQd7ko8aTIOIayfxJiv/u0yqwuBuBW2bFrL/41b1cKGK5+Iq2a+PdFENUPenKXISkACGaMnQF4Y/KVF98UwCiGLf957yFWc2sD6TFbjNDbAENSccvg1J3fBb+djbtzKzldl29ntp2mKVGSVASiKCRa6hSfgQulHiidFqFIKgpYJ1uATRr3UFr/NRVt1WbrgLnzY74OCX7y02c/xiYQMMEPRl/P8hHJu+KjQ3PBWsBvmsRN0QMUJv3PEjUPE3AY8sw49NoxiJZzJr7574vUBuM/dk0byYI6K/gwmUrPIhQjljzZqinS8JJJ4FjGjCdzXRhT5Q+PZvt5bF1rMOZXayNJZa+cICtmiJoU3vO2Yf6TXC3wY1veKvmcs24nws5lp4keJePTKAi1Ig7VoSxwAlgs3EGANIh7oBKx9zWnXQYMdmxbYsvLXAWcnnM+PcSCvooLmXWso3BQBeRuUUSS2oLaBpsFMsiniLNbA1cW4fwMkgUGz4oEDRi8wTD89E/1J2oNxzqtWRPawcVKpMpnBbDJHrWJPEHMw=
      email:
        secure: lomzDl71N995SzRczm7VE9OZE+PzMo4X8t3zU97agu/FMH5Qcj8BLwE+uVDTnA9Vblyj62ZsFKsNjP2Qp53Vcd+jHM4EJNWNRZYpEMIRO3LngX43r83qoFEHUvPu9s1oaa04a6FojcsJx0wl6B6Ke2AX74MXnJDLb9iZBy1mkpLUMVccVhSfhdoIzhkq3dhUw+6d8C024tNMHcgDW3VnRAsWFtiL7dCMpjLOdI+UxlkeGkQkxXXuRsZ0ZdjoSoM8NSkiYMc8x6EnekyRDoHTujX3OFxuU6+GAjrUmVzNmJWrBIqHVb0DXBQxjEaG3d/cNu5UsQyZYq5sxRRH0BaLs7F4oIQg95etasEtTtUkmsZ3pshVlsweiLU366UdbfuAf5hrJjqLrU12BKZyLjaAwyeKz031r8dA4sJtGIp5uVdXobQQTH6r958A88byJ20uaYSqhqjhZo3hkWXIQP0WQN2Ej/g57HbVNLB/nPKkMILfk/tpp7nBDLT0QrjbZxeo1dwCHqsBEV6z7ZyWyFf4xwpDsir4txL4t8ElzeGdlACjCqAJvIh5w9YzfrwijtoVMvvP6pWvn/iI640d4rsdIDe8egxgqZ1R/TMd/tdHYX+eI+ZfFmCVGj36/uXwdG7KIoIZVjRQ2tvWr9ZuydEPWPSRVGT4ycFeu6wbm3elM3I=
      skip_cleanup: true
      on:
        tags: true
        all_branches: true
        repo: parse-community/parse-server
